version: '3.7'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      # External (host) port: Internal (container) port
      - "7077:7077" # Port for Spark Master (used for connecting your Python scripts or other clients)
      - "8080:8080" # Web interface for monitoring the Spark Master

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      # The port mapping here is optional. Spark Master handles worker assignments automatically.
      # Exposing this port allows direct access to this specific worker's web interface.
      - "8081:8081" # Web interface for Spark Worker 1 (also accessible via the Master's Applications tab)

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      # Optional port mapping to access the second worker's web interface.
      # The web UI of Spark Master can also display worker details under the Applications tab.
      - "8082:8081" # Web interface for Spark Worker 2
