version: '3.7'
services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports: # <porta-externa (host)>:<porta-interna (container)>
      - "7077:7077" # Porta para o MASTER (aqui você conecta seu script python)
      - "8080:8080" # Interface web do Spark Master (Aqui você monitora os dados)

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
    # P.S. você pode remover a porta, caso você não precise saber qual worker está executando,
    # pois o spark-master faz isso pra você, neste caso, eu criei dois workers para poder
    # acessar separadamente a interface quando eu quiser pelo localhost.
      - "8081:8081" # Interface web do Spark WORKER (se você for pelo localhost:8080 também chega aqui clicando nas APPLICATIONS )
  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    # P.S. você pode remover a porta, caso você não precise saber qual worker está executando,
    # pois o spark-master faz isso pra você, neste caso, eu criei dois workers para poder
    # acessar separadamente a interface quando eu quiser pelo localhost.
    ports:
      - "8082:8081" # Interface web do Spark WORKER (se você for pelo localhost:8080 também chega aqui clicando nas APPLICATIONS )
